import { writeFile } from 'fs/promises';
import type { Theme } from './themes';
import { objectToCSSVars } from './objectToCSSVars';

/**
 * Generate a CSS file from a {@link Theme}.
 * @param theme - The theme to generate the CSS file from.
 * @param selector - The selector to use for the CSS variables (default: `:root`).
 */
export const generateCSS = (theme: Theme, selector: string = ':root'): string => {
    const vars = objectToCSSVars(theme).map(([key, value]) => `${key}: ${value};`).join('\n    ');
    return `/* ${theme?.themeName || 'Theme'} variables, generated by \`pte\` */
/* This is automatically generated. Do not edit directly. */

${selector} {
    ${vars}
}
`;
};

/**
 * Export a {@link Theme} to a static CSS file.
 * @param output - The path to the output file (e.g. `public/theme.css`).
 * @param theme - The theme to export.
 * @param selector - The selector to use for the CSS variables (default: `:root`).
 */
export const exportCSS = async (output: string, theme: Theme, selector: string = ':root'): Promise<void> => {
    const css = generateCSS(theme, selector);
    await writeFile(output, css);
};
