import type { Theme } from './themes';
import { objectToCSSVars } from './objectToCSSVars';

/**
 * Generate a CSS file from a {@link Theme}.
 * @param theme - The theme to generate the CSS file from.
 * @param selector - The selector to use for the CSS variables (default: `:root`).
 */
export const generateCSS = <T extends Record<string, any> = Theme>(theme: T, selector: string = ':root'): string => {
    const vars = objectToCSSVars(theme).map(([key, value]) => `${key}: ${value};`).join('\n    ');
    return `/* ${theme?.themeName || 'Theme'} variables, generated by \`pte\` */
/* This is automatically generated. Do not edit directly. */

${selector} {
    ${vars}
}
`;
};
